### ISSUE TITLE
Expo integration?

### ISSUE THREAD

**Issue by lamaji** [hkthea/react-native-abal-scanner-sdk#1]
Can I use this package in my expo project without ejecting?

The `import RNAbalScannerSdk...` not working
I got: 

> Could not find a declaration file for module 'react-native-abal-scanner-sdk'. '.../node_modules/react-native-abal-scanner-sdk/index.js' implicitly has an 'any' type.

**Comment by hkthea** [comment]
i haven't tried this with expo, and have no knowledge to do so, i'm sorry

**Comment by lamaji** [comment]
Thanks @hkthea for your reply,
Please, I need a quick documentation for this lines. 
What difference between start and open / stop and close.
If I write all this with this order sould work in my PDA?
```
public scan function() {
RNAbalScannerSdk.startScan();
RNAbalScannerSdk.stopScan();
RNAbalScannerSdk.openScan();
RNAbalScannerSdk.closeScan();
RNAbalScannerSdk.on('scan.rcv.message', event=>{
  console.log(event);      
})
}
```

**Comment by hkthea** [comment]
i'm sorry i am little forget about this lib, the device i bought it's from china, and only for dummy, not to real production project, but i have bridging successfully, 

and i have tried to looking for the dummy project, but cannot found them. 

as i remembered, the method is 

startScan(); ---- it is for soft scan, with out hardware scan button, so you can using button to trigger scan, and if it's not found any barcode you have to use stopScan() method, 
and for openScan and closeScan it is for open library, so you have to do is

```
function App(){

  useEffect(()=>{
    RNAbalScannerSdk.openScan();
    const handler=event=>{
       console.log(event);     
    }
    RNAbalScannerSdk.on('scan.rcv.message', handler);    
    return ()=>{
       RNAbalScannerSdk.off('scan.rcv.message',handler);
       RNAbalScannerSdk.closeScan();
    }
  })

  return(
     <View>
          { RNAbalScannerSdk.isCompatible && <Text>Scanner Compatible</Text> }
         <Button title="Scan" onPress={()=>RNAbalScannerSdk.startScan()}/>
         <Button title="Stop Scan" onPress={()=>RNAbalScannerSdk.stopScan()}/>
     </View>
     
  )
}
```

i'm not sure it will work, because the PDA i have, have been broken. hope it work and compatible with your PDA,

**Comment by lamaji** [comment]
Thank you so much @hkthea. that's realy helped me.
The lib is compatibe and the button start the scan as espected.

I need to show just the barcode. But I don't know what is the event result. 
(I don't have PDA to do debug. I export apk and I send it to another one to do test)

I have something like this:
```javascript
public scan function() {
    RNAbalScannerSdk.startScanner();
    RNAbalScannerSdk.on('scan.rcv.message', event=>{
        this.setState({barcode: event})
    })
}

render(){
    return(
      <View>
           <Text>Barcode: {this.state.barcode}</Text>
           <Button title="Start Scan" onPress={()=>this.scan()}/>
           <Button title="Stop Scan" onPress={()=>RNAbalScannerSdk.stopScan()}/>
      </View>
    );
}
```

**Comment by hkthea** [comment]
this function i think, it should place in componentdidmount or it will make some bugs
```
RNAbalScannerSdk.on('scan.rcv.message', event=>{
       const {data}=event;
        this.setState({barcode: data});
    })
```
and for barcode data field is data, 
```
public scan function() {
    RNAbalScannerSdk.startScanner();
    
}

render(){
    return(
      <View>
           <Text>Barcode: {this.state.barcode}</Text>
           <Button title="Start Scan" onPress={()=>this.scan()}/>
           <Button title="Stop Scan" onPress={()=>RNAbalScannerSdk.stopScan()}/>
      </View>
    );
}

```

**Comment by lamaji** [comment]
There is one more issue and hope this is the last one

- The package is compatible with our PDA.
- I can start the scanner using scan method.
- but there is **No returned data**.

I need to change something in `RNAbalScannerSdkModule.java > onReceive()` ?

I'm very sorry for distrubing you.

**Comment by hkthea** [comment]
Feel free to fork my repository, i'm afraid your PDA use different intent event message.  if you have example code with SDK from suplier you can see the different.
